version: "3.9"

services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit-ollama
    ports:
      - "8501:8501"
    environment:
      - OLLAMA_URL=http://host.containers.internal:11434/api/generate
    restart: unless-stopped
